jobs:

# All tasks on Windows....
- job: build_all_windows
  displayName: Build all tasks (Windows)
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100'
  - script: choco install protoc --version 3.6.0 -y
  - script: choco install unzip
  - task: BatchScript@1
    inputs:
      filename: 'scripts/download_binary.bat'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/p:NoBuild=false --configuration Debug'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'test/*Tests/*.csproj'
      arguments: '--configuration Debug'
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100'
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/p:NoBuild=false --configuration Debug'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'test/*Tests/*.csproj'
      arguments: '--configuration Debug'
# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  pool:
    vmImage: macos-10.13
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.100' 
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'AElf.sln'
      arguments: '/p:NoBuild=false --configuration Debug'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'test/*Tests/*.csproj'
      arguments: '--configuration Debug'
      
